name: bloodbankapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_database: ^11.0.4
  firebase_core: ^3.4.0
  firebase_messaging: ^15.0.3
  firebase_auth: ^5.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  mongo_dart: ^0.10.3
  geolocator: ^13.0.2
  http: ^1.2.2
  shared_preferences: ^2.3.3
  webview_flutter: ^4.10.0
  webview_flutter_wkwebview: ^3.16.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


   uses-material-design: true

   assets:
     - assets/logo/
